# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html spring\u914D\u7F6E\u7684\u6587\u6863
server:
  port: 10086

spring:
  servlet:
    multipart:
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
  devtools:
    restart:
      enabled: true  #设置开启热部署

  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 3
      minIdle: 1
      maxActive: 500
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 1
      testOnBorrow: true
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ordering?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&rewriteBatchedStatements=true
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:xml/*.xml